project_id = "jratyxzmjkjzpaqclsio"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.analyze-image]
verify_jwt = true

[functions.analyze-video]  
verify_jwt = true

[functions.check-video-operation]
verify_jwt = true

[db]
port = 54322
shadow_port = 54320
major_version = 15